server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: gateway
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8081

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          default-filters:
          routes:
            - id: auth-service-v1
              uri: lb://auth-service
              predicates:
                - Path=/api/v1/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${EUREKA_PORT:8761}/eureka
      register-with-eureka: false
      fetch-registry: true