services:
  mysql:
    image: mysql:8.0
    container_name: ecomhub_auth_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ecomhub_auth
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
  redis:
    image: redis:7.0-alpine
    container_name: redis_service
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  mysql-data:
  redis_data:
