server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: auth-service
  data:
    redis:
      port: 6379
      host: localhost
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ecomhub_auth}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8081
  jpa:
    hibernate:
      ddl-auto: none
#eureka:
#  client:
#    service-url:
#        defaultZone: http://localhost:${EUREKA_PORT:8761}/eureka
#    register-with-eureka: false
#    fetch-registry: true


#    enabled: false
logging:
  level:
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
    org.springframework.security.authorization: debug