server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: auth-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ecomhub_auth}?useSSL=false&serverTimezone=UTC
    username: ${DB_USER:root}
    password: ${DB_PASS:root}
  jpa:
    hibernate:
      ddl-auto: none
eureka:
  client:
    service-url:
        defaultZone: http://localhost:${EUREKA_PORT:8761}/eureka
    register-with-eureka: false
    fetch-registry: true
    enabled: false

